<?xml version="1.0" encoding="utf-8"?><Database Name="LCSK" EntityNamespace="LiveChat.Core.Data" ContextNamespace="LiveChat.Core.Data" Class="LCSKDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=devpc\sqlexpress;Initial Catalog=LCSK;Integrated Security=True" SettingsObjectName="LiveChat.Core.Properties.Settings" SettingsPropertyName="LCSKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LCSK_CannedMessages" Member="LCSK_CannedMessages">
    <Type Name="LCSK_CannedMessage">
      <Column Name="OperatorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="ShowPrompt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_WebRequests" Member="LCSK_WebRequests">
    <Type Name="LCSK_WebRequest">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VisitorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RequestedDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Page" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DomainName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Referrer" Type="System.String" DbType="VarChar(350) NOT NULL" CanBeNull="false" />
      <Association Name="LCSK_Visitor_LCSK_WebRequest" Member="LCSK_Visitor" ThisKey="VisitorId" OtherKey="Id" Type="LCSK_Visitor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_ChatMessages" Member="LCSK_ChatMessages">
    <Type Name="LCSK_ChatMessage">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Posted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LCSK_ChatRequest_LCSK_ChatMessage" Member="LCSK_ChatRequest" ThisKey="Id" OtherKey="Id" Type="LCSK_ChatRequest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_ChatRequests" Member="LCSK_ChatRequests">
    <Type Name="LCSK_ChatRequest">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VisitorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OperatorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Requested" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="InitiatedFromVisitor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Accepted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Closed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="LCSK_ChatRequest_LCSK_ChatMessage" Member="LCSK_ChatMessage" ThisKey="Id" OtherKey="Id" Type="LCSK_ChatMessage" Cardinality="One" />
      <Association Name="LCSK_Department_LCSK_ChatRequest" Member="LCSK_Department" ThisKey="Id" OtherKey="Id" Type="LCSK_Department" IsForeignKey="true" />
      <Association Name="LCSK_Operator_LCSK_ChatRequest" Member="LCSK_Operator" ThisKey="OperatorId" OtherKey="Id" Type="LCSK_Operator" IsForeignKey="true" />
      <Association Name="LCSK_Visitor_LCSK_ChatRequest" Member="LCSK_Visitor" ThisKey="Id" OtherKey="Id" Type="LCSK_Visitor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_Departments" Member="LCSK_Departments">
    <Type Name="LCSK_Department">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="LCSK_Department_LCSK_ChatRequest" Member="LCSK_ChatRequest" ThisKey="Id" OtherKey="Id" Type="LCSK_ChatRequest" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_Operators" Member="LCSK_Operators">
    <Type Name="LCSK_Operator">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsOnline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsManager" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="LCSK_Operator_LCSK_ChatRequest" Member="LCSK_ChatRequests" ThisKey="Id" OtherKey="OperatorId" Type="LCSK_ChatRequest" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_Operators_Departments" Member="LCSK_Operators_Departments">
    <Type Name="LCSK_Operators_Department">
      <Column Name="DepartmentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OperatorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_QuickLinks" Member="LCSK_QuickLinks">
    <Type Name="LCSK_QuickLink">
      <Column Name="OperatorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LinkName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LCSK_Visitors" Member="LCSK_Visitors">
    <Type Name="LCSK_Visitor">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TranscriptByEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="idAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Browser" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="InChat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProActiveRequest" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="LCSK_Visitor_LCSK_WebRequest" Member="LCSK_WebRequests" ThisKey="Id" OtherKey="VisitorId" Type="LCSK_WebRequest" />
      <Association Name="LCSK_Visitor_LCSK_ChatRequest" Member="LCSK_ChatRequest" ThisKey="Id" OtherKey="Id" Type="LCSK_ChatRequest" Cardinality="One" />
    </Type>
  </Table>
</Database>