//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveChat.WebSite.OperatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperatorServiceReference.IOperator")]
    public interface IOperator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/GetOnlineOperator", ReplyAction="http://tempuri.org/IOperator/GetOnlineOperatorResponse")]
        LiveChat.Entities.OperatorEntity[] GetOnlineOperator();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/IsOperatorOnline", ReplyAction="http://tempuri.org/IOperator/IsOperatorOnlineResponse")]
        bool IsOperatorOnline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/Create", ReplyAction="http://tempuri.org/IOperator/CreateResponse")]
        int Create(string name, string password, string email, bool isAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/UpdateStatus", ReplyAction="http://tempuri.org/IOperator/UpdateStatusResponse")]
        void UpdateStatus(int operatorId, bool isOnline);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/LogIn", ReplyAction="http://tempuri.org/IOperator/LogInResponse")]
        LiveChat.Entities.OperatorEntity LogIn(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/Remove", ReplyAction="http://tempuri.org/IOperator/RemoveResponse")]
        bool Remove(int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/GetChatChannel", ReplyAction="http://tempuri.org/IOperator/GetChatChannelResponse")]
        LiveChat.Entities.ChannelEntity[] GetChatChannel(int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperator/GetOnlineDepartment", ReplyAction="http://tempuri.org/IOperator/GetOnlineDepartmentResponse")]
        LiveChat.Entities.DepartmentEntity[] GetOnlineDepartment();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOperatorChannel : LiveChat.WebSite.OperatorServiceReference.IOperator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OperatorClient : System.ServiceModel.ClientBase<LiveChat.WebSite.OperatorServiceReference.IOperator>, LiveChat.WebSite.OperatorServiceReference.IOperator {
        
        public OperatorClient() {
        }
        
        public OperatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LiveChat.Entities.OperatorEntity[] GetOnlineOperator() {
            return base.Channel.GetOnlineOperator();
        }
        
        public bool IsOperatorOnline() {
            return base.Channel.IsOperatorOnline();
        }
        
        public int Create(string name, string password, string email, bool isAdmin) {
            return base.Channel.Create(name, password, email, isAdmin);
        }
        
        public void UpdateStatus(int operatorId, bool isOnline) {
            base.Channel.UpdateStatus(operatorId, isOnline);
        }
        
        public LiveChat.Entities.OperatorEntity LogIn(string name, string password) {
            return base.Channel.LogIn(name, password);
        }
        
        public bool Remove(int operatorId) {
            return base.Channel.Remove(operatorId);
        }
        
        public LiveChat.Entities.ChannelEntity[] GetChatChannel(int operatorId) {
            return base.Channel.GetChatChannel(operatorId);
        }
        
        public LiveChat.Entities.DepartmentEntity[] GetOnlineDepartment() {
            return base.Channel.GetOnlineDepartment();
        }
    }
}
