//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorConsole.RequestService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageRequestEntity", Namespace="http://schemas.datacontract.org/2004/07/LiveChat.Entities")]
    [System.SerializableAttribute()]
    public partial class PageRequestEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferrerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisitorIpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageRequested {
            get {
                return this.PageRequestedField;
            }
            set {
                if ((object.ReferenceEquals(this.PageRequestedField, value) != true)) {
                    this.PageRequestedField = value;
                    this.RaisePropertyChanged("PageRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referrer {
            get {
                return this.ReferrerField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferrerField, value) != true)) {
                    this.ReferrerField = value;
                    this.RaisePropertyChanged("Referrer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestedDate {
            get {
                return this.RequestedDateField;
            }
            set {
                if ((this.RequestedDateField.Equals(value) != true)) {
                    this.RequestedDateField = value;
                    this.RaisePropertyChanged("RequestedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent {
            get {
                return this.UserAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgentField, value) != true)) {
                    this.UserAgentField = value;
                    this.RaisePropertyChanged("UserAgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitorIp {
            get {
                return this.VisitorIpField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitorIpField, value) != true)) {
                    this.VisitorIpField = value;
                    this.RaisePropertyChanged("VisitorIp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequestService.IWebRequest")]
    public interface IWebRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebRequest/LogRequest", ReplyAction="http://tempuri.org/IWebRequest/LogRequestResponse")]
        void LogRequest(OperatorConsole.RequestService.PageRequestEntity page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebRequest/GetRequests", ReplyAction="http://tempuri.org/IWebRequest/GetRequestsResponse")]
        OperatorConsole.RequestService.PageRequestEntity[] GetRequests(System.DateTime since);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWebRequestChannel : OperatorConsole.RequestService.IWebRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebRequestClient : System.ServiceModel.ClientBase<OperatorConsole.RequestService.IWebRequest>, OperatorConsole.RequestService.IWebRequest {
        
        public WebRequestClient() {
        }
        
        public WebRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LogRequest(OperatorConsole.RequestService.PageRequestEntity page) {
            base.Channel.LogRequest(page);
        }
        
        public OperatorConsole.RequestService.PageRequestEntity[] GetRequests(System.DateTime since) {
            return base.Channel.GetRequests(since);
        }
    }
}
