<?xml version="1.0" encoding="utf-8"?><Database Name="hlsim" Class="LCSKDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=devpc\sqlexpress;Initial Catalog=hlsim;Integrated Security=True" SettingsObjectName="LCSK.Providers.Sql.Properties.Settings" SettingsPropertyName="hlsimConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LiveChat_ChatMessages" Member="LiveChat_ChatMessages">
    <Type Name="LiveChat_ChatMessage">
      <Column Name="MessageID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChatID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FromName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(3000) NOT NULL" CanBeNull="false" />
      <Column Name="SentDate" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LiveChat_ChatRequests" Member="LiveChat_ChatRequests">
    <Type Name="LiveChat_ChatRequest">
      <Column Name="ChatID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VisitorIP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VisitorName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VisitorEmail" Type="System.String" DbType="VarChar(225) NOT NULL" CanBeNull="false" />
      <Column Name="VisitorUserAgent" Type="System.String" DbType="VarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="AcceptDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ClosedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LiveChat_LogAccess" Member="LiveChat_LogAccesses">
    <Type Name="LiveChat_LogAccess">
      <Column Name="LogAccessID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageRequested" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DomainRequested" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="RequestedTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Referrer" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="VisitorUserAgent" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VisitorIP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LiveChat_Operators" Member="LiveChat_Operators">
    <Type Name="LiveChat_Operator">
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OperatorPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OperatorEmail" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsOnline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>